name: Laravel

on:
  push:
    branches: [ "master" ]

jobs:
  ci-reuse:
    uses: ./.github/workflows/ci.yml

  laravel-deploy:
    runs-on: ubuntu-latest
    needs: ci-reuse

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_DIR }}
          git pull origin master
          composer install
          npm install
          npm run build
          php artisan config:cache
          php artisan route:cache
